name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: 'master'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        env:
          PUBLIC_FIREBASE_API_KEY: ${{ secrets.PUBLIC_FIREBASE_API_KEY }}
          PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.PUBLIC_FIREBASE_AUTH_DOMAIN }}
          PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.PUBLIC_FIREBASE_PROJECT_ID }}
          PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.PUBLIC_FIREBASE_STORAGE_BUCKET }}
          PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          PUBLIC_FIREBASE_APP_ID: ${{ secrets.PUBLIC_FIREBASE_APP_ID }}
          PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.PUBLIC_FIREBASE_MEASUREMENT_ID }}
        run: |
          pnpm run build
          touch build/.nojekyll

      - name: Commit generated files only
        run: |
          echo "> Start remove unused files..."
          rm -rf markdowns
          rm -rf .github/workflows
          rm -rf .svelte-kit
          rm -rf screenshoot
          rm -rf scripts
          rm -rf static
          rm -rf src
          rm -rf node_modules
          rm .all-contributorsrc
          rm .editorconfig
          rm .eslintignore
          rm .eslintrc.cjs
          rm .gitignore
          rm .kodiak.toml
          rm .npmrc
          rm .prettierignore
          rm .prettierrc
          rm package.json
          rm pnpm-lock.yaml
          rm postcss.config.js
          rm svelte.config.js
          rm tailwind.config.js
          rm tsconfig.json
          rm vite.config.ts
          cp -r build/. ./
          rm -rf build
          git config --local user.email "mazipanneh@gmail.com"
          git config --local user.name "Irfan Maulana"
          git add -A
          git commit -m "[CI]: Auto Deploy 🚀"
          echo "> Finish commit changes to repo"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          force: true
          repository: mazipan-quran-offline/mazipan-quran-offline.github.io
