name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: 'master'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: |
          pnpm run build
          touch build/.nojekyll

      - name: Commit generated files only
        run: |
          echo "> Start remove unused files..."
          rm -rf markdownds
          rm -rf .github/workflows
          rm -rf screenshoot
          rm -rf scripts
          rm -rf static
          rm -rf src
          rm .all-contributorsrc
          rm .editorconfig
          rm .eslintignore
          rm .eslintrc.cjs
          rm .gitignore
          rm .kodiak.toml
          rm .npmrc
          rm .prettierignore
          rm .prettierrc
          rm package.json
          rm pnpm-lock.yaml
          rm postcss.config.js
          rm svelte.config.js
          rm tailwind.config.js
          rm tsconfig.json
          rm vite.config.ts
          cp -r build/. ./
          rm -rf build
          git config --local user.email "mazipanneh@gmail.com"
          git config --local user.name "Irfan Maulana"
          git add -A
          git commit -m "[CI]: Auto Deploy 🚀"
          echo "> Finish commit changes to repo"

      - name: GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          force: true
          repository: mazipan-quran-offline/mazipan-quran-offline.github.io
